import './globals.css'
import styles from './layout.module.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: 'https://howtodrawforkids.com/wp-content/uploads/2020/08/how-to-draw-a-cat.jpg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.navbar}>
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          <Link href="/product">Product</Link>
        </nav>
        {children}
        <footer className={styles.footer}>
          <p>&copy; 2023</p>
        </footer>
      </body>
    </html>
  )
}
